#!/bin/bash

echo "**** start build modem ****"

MODEM_TOP=/home/user/work/code/iot3/billy/mtk8765_o1_mp1_modem/TK_MD_BASIC_MOLY.LR12A.R2.MP.V38

DATABASE=$MODEM_TOP/mcu/build/TK_MD_BASIC/LWTG_8765/dhl/database

ALPS_TOP=/home/user/work/code/iot3/billy/mtk8765_mp_o1_mp1
modemRenameCopy=$ALPS_TOP/device/mediatek/build/build/tools/modemRenameCopy.pl
modem_Androidmk=$ALPS_TOP/device/mediatek/build/build/tools/modem/modem_Android.mk
MODEM_DIR=$ALPS_TOP/vendor/mediatek/proprietary/modem

ProjectConfigmk=$ALPS_TOP/device/mediateksample/h801v1_factory/ProjectConfig.mk


sim_hotplug=no
cogps_type=0
c2k_type=yes
sim_swap=no
special_fun=no

cd $MODEM_TOP
source $MODEM_TOP/mcu/teksun_modem/mdcfg.sh
test=0
modem_code_name=${board_type}_${rf_type}

if [ ! -d "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}" ];then
   echo "------teksun: 没有modem代码文件夹:"${modem_code_name}",请检查!"
   exit
fi

echo "*** checkout modem from service ***"
git checkout -f $MODEM_TOP/mcu/make/projects/
git checkout -f $MODEM_TOP/mcu/common/driver/devdrv/usim/src/icc_switchControl_al.c
git checkout -f $MODEM_TOP/mcu/pcore/custom/modem/

rm -rf $MODEM_TOP/mcu/temp_modem/
rm -rf $MODEM_TOP/mcu/build/
rm -rf $MODEM_TOP/mcu/build_internal/

echo "*** remove Original custom modem ***"
if [ $c2k_type = yes ];then
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/cl1_rf/MT6739_C2K_MT6177M_TB
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/el1_rf/MT6739_LTE_MT6177M_TB
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/l1_rf/MT6739_2G_MT6177M_SP_TB
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/mml1_rf/MT6739_MMRF_MT6177M_TB
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/tl1_rf/MT6739_UMTS_TDD_MT6177M_TB
   	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/ul1_rf/MT6739_UMTS_FDD_MT6177M_TB
else
    rm -rf $MODEM_TOP/mcu/pcore/custom/modem/cl1_rf/MT6739_C2K_MT6177M
    rm -rf $MODEM_TOP/mcu/pcore/custom/modem/el1_rf/MT6739_LTE_MT6177M
    rm -rf $MODEM_TOP/mcu/pcore/custom/modem/l1_rf/MT6739_2G_MT6177M_SP
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/mml1_rf/MT6739_MMRF_MT6177M
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/tl1_rf/MT6739_UMTS_TDD_MT6177M
	rm -rf $MODEM_TOP/mcu/pcore/custom/modem/ul1_rf/MT6739_UMTS_FDD_MT6177M
fi

echo "*** remove Own custom modem ***"
if [ $c2k_type = yes ];then
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/cl1_rf/MT6739_C2K_MT6177M_TB/"  "$MODEM_TOP/mcu/pcore/custom/modem/cl1_rf/MT6739_C2K_MT6177M_TB/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/el1_rf/MT6739_LTE_MT6177M_TB/"  "$MODEM_TOP/mcu/pcore/custom/modem/el1_rf/MT6739_LTE_MT6177M_TB/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/l1_rf/MT6739_2G_MT6177M_SP_TB/"  "$MODEM_TOP/mcu/pcore/custom/modem/l1_rf/MT6739_2G_MT6177M_SP_TB/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/mml1_rf/MT6739_MMRF_MT6177M_TB/"  "$MODEM_TOP/mcu/pcore/custom/modem/mml1_rf/MT6739_MMRF_MT6177M_TB/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/tl1_rf/MT6739_UMTS_TDD_MT6177M_TB/"  "$MODEM_TOP/mcu/pcore/custom/modem/tl1_rf/MT6739_UMTS_TDD_MT6177M_TB/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/ul1_rf/MT6739_UMTS_FDD_MT6177M_TB/"  "$MODEM_TOP/mcu/pcore/custom/modem/ul1_rf/MT6739_UMTS_FDD_MT6177M_TB/"
else
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/cl1_rf/MT6739_C2K_MT6177M_TB/"  "$MODEM_TOP/mcu/pcore/custom/modem/cl1_rf/MT6739_C2K_MT6177M_TB/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/el1_rf/MT6739_LTE_MT6177M/"  "$MODEM_TOP/mcu/pcore/custom/modem/el1_rf/MT6739_LTE_MT6177M/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/l1_rf/MT6739_2G_MT6177M_SP/"  "$MODEM_TOP/mcu/pcore/custom/modem/l1_rf/MT6739_2G_MT6177M_SP/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/mml1_rf/MT6739_MMRF_MT6177M/"  "$MODEM_TOP/mcu/pcore/custom/modem/mml1_rf/MT6739_MMRF_MT6177M/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/tl1_rf/MT6739_UMTS_TDD_MT6177M/"  "$MODEM_TOP/mcu/pcore/custom/modem/tl1_rf/MT6739_UMTS_TDD_MT6177M/"
	cp -rf "$MODEM_TOP/mcu/teksun_modem/${modem_code_name}/ul1_rf/MT6739_UMTS_FDD_MT6177M/"  "$MODEM_TOP/mcu/pcore/custom/modem/ul1_rf/MT6739_UMTS_FDD_MT6177M/"
fi

if [ $sim_hotplug = yes ];then
		grep -nr SIM_HOT_SWAP $MODEM_TOP/mcu/make/projects
	if [ $c2k_type = yes ];then
   		echo "*** enable sim hotplus TK_MD_BASIC(LWCTG_TB_8765).mak***"
   		sed -i '/DUAL_SIM_HOT_SWAP_CO_DECK/c\DUAL_SIM_HOT_SWAP_CO_DECK = TRUE'     $MODEM_TOP/mcu/make/projects/TK_MD_BASIC\(LWCTG_TB_8765\).mak
   		sed -i '/SIM_HOT_SWAP =/c\SIM_HOT_SWAP = SIM_SLOT_2'     $MODEM_TOP/mcu/make/projects/TK_MD_BASIC\(LWCTG_TB_8765\).mak
	else
   		echo "*** enable sim hotplus TK_MD_BASIC(LWTG_8765).mak***"
		sed -i '/DUAL_SIM_HOT_SWAP_CO_DECK/c\DUAL_SIM_HOT_SWAP_CO_DECK = TRUE'     $MODEM_TOP/mcu/make/projects/TK_MD_BASIC\(LWTG_8765\).mak
   		sed -i '/SIM_HOT_SWAP =/c\SIM_HOT_SWAP = SIM_SLOT_2'     $MODEM_TOP/mcu/make/projects/TK_MD_BASIC\(LWTG_8765\).mak
	fi
		grep -nr SIM_HOT_SWAP $MODEM_TOP/mcu/make/projects
fi

if [ $sim_swap = yes ];then
   echo "*** enable sim swap ***"
   sed -i '/kal_bool[	 ]*sim_physicalSlotChanged;*/c\kal_bool sim_physicalSlotChanged=KAL_TRUE;' $MODEM_TOP/mcu/common/driver/devdrv/usim/src/icc_switchControl_al.c
fi

cd $MODEM_TOP/mcu

echo "*** build modem ***"
rm -rf build
rm -rf build_internal

if [ $c2k_type = yes ];then
	echo "*** build modem LWCTG_TB_8765 press any key continue***"
	read
	./m TK_MD_BASIC\(LWCTG_TB_8765\).mak new
else
	echo "*** build modem LWTG_8765 press any key continue***"
	read
	./m TK_MD_BASIC\(LWTG_8765\).mak new
fi

rm -rf $MODEM_TOP/mcu/temp_modem
rm -rf $MODEM_TOP/temp_modem

cd $ALPS_TOP
if [ $c2k_type = yes ];then
	echo "*** modemRenameCopy LWCTG_TB_8765 press any key continue***"
	read
	perl $modemRenameCopy $MODEM_TOP/mcu TK_MD_BASIC\(LWCTG_TB_8765\)
else
	echo "*** modemRenameCopy LWTG_8765 press any key continue***"
	read
	perl $modemRenameCopy $MODEM_TOP/mcu TK_MD_BASIC\(LWTG_8765\)
fi

echo "*** copy apps library to modem ***"
cp -ar $MODEM_TOP/mcu/apps/* $MODEM_TOP/mcu/temp_modem

echo "*** checkout modem from service ***"
cd $MODEM_TOP
git checkout -f $MODEM_TOP/mcu/make/projects/
git checkout -f $MODEM_TOP/mcu/common/driver/devdrv/usim/src/icc_switchControl_al.c
git checkout -f $MODEM_TOP/mcu/pcore/custom/modem/

echo "*** mv modem to alsp"
rm -rf $MODEM_DIR/*
mv $MODEM_TOP/mcu/temp_modem $MODEM_DIR/h801v1_a_modem

cp $modem_Androidmk $MODEM_DIR/Android.mk

sed -i '/CUSTOM_MODEM/c CUSTOM_MODEM=h801v1_a_modem' $ProjectConfigmk

grep -nr CUSTOM_MODEM $ProjectConfigmk

