/* generated by mediatek */

package gn.com.android.mmitest.item;

import android.os.SystemProperties;

import com.android.internal.util.XmlUtils;

import gn.com.android.mmitest.utils.DswLog;
import android.util.Xml;

import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserException;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
public final class FeatureOption {

    /**
     * check if MTK_GEMINI_SUPPORT is turned on or not
     */
    public static final boolean MTK_GEMINI_SUPPORT = true;
    /**
     * check if GN_APP_THEME_SUPPORT is turned on or not
     */
    public static final boolean GN_APP_THEME_SUPPORT = true;

    // Gionee zhangke 20160104 add for CR01617603 start
    private static final String TAG = "FeatureOption";
    public static  String GN_MMI_CONFIG_FILE = "/system/etc/gnmmiConfig.xml";

    private static final String GN_RW_GN_MMI_AUTOTEST2 = "GN_RW_GN_MMI_AUTOTEST2";
    //Gionee zhangke 20160310 add for CR01650400 start
    private static final String GN_RW_GN_MMI_RPMB = "GN_RW_GN_MMI_RPMB";
    //Gionee zhangke 20160310 add for CR01650400 end
    private static final String GN_RW_GN_MMI_BACKUP_TO_PRODUCTINFO = "GN_RW_GN_MMI_BACKUP_TO_PRODUCTINFO";
    private static final String GN_RW_GN_MMI_SW_VERSION = "GN_RW_GN_MMI_SW_VERSION";
    //Gionee <GN_BSP_MMI> <chengq> <20170412> add for ID 91383 begin
    private static final String GN_RW_GN_MMI_GM3 = "GN_RW_GN_MMI_GM3.0";
    private static final String GN_RW_GN_MMI_EFUSE = "GN_RW_GN_MMI_EFUSE";
    //Gionee <GN_BSP_MMI> <chengq> <20170412> add for ID 91383 end
    private static final String GN_RW_GN_MMI_WCDMA = "GN_RW_GN_MMI_WCDMA";
    private static final String GN_RW_GN_MMI_CDMA = "GN_RW_GN_MMI_CDMA";
    private static final String GN_RW_GN_MMI_TDSCDMA = "GN_RW_GN_MMI_TDSCDMA";
    private static final String GN_RW_GN_MMI_LTETDD = "GN_RW_GN_MMI_LTETDD";
    private static final String GN_RW_GN_MMI_LTEFDD = "GN_RW_GN_MMI_LTEFDD";
    //Gionee <Oversea_Bug> <tanbotao> <20161130> for 36474 beign
    private static final String GN_RW_GN_MMI_ANT = "GN_RW_GN_MMI_ANT";
    //Gionee <Oversea_Bug> <tanbotao> <20161130> for 36474 beign
    private static final String GN_RW_GN_MMI_SCREEN_BRIGHTNESS = "GN_RW_GN_MMI_SCREEN_BRIGHTNESS";
    private static final String GN_RW_GN_MMI_LCD = "GN_RW_GN_MMI_LCD";
    private static final String GN_RW_GN_MMI_KEYTEST = "GN_RW_GN_MMI_KEYTEST";
    private static final String GN_RW_GN_MMI_KEYTEST_HALL = "GN_RW_GN_MMI_KEYTEST_HALL";
    private static final String GN_RW_GN_MMI_KEYTEST_CAMERA = "GN_RW_GN_MMI_KEYTEST_CAMERA";
    private static final String GN_RW_GN_MMI_KEYTEST_SEARCH = "GN_RW_GN_MMI_KEYTEST_SEARCH";
    private static final String GN_RW_GN_MMI_KEYTEST_APP = "GN_RW_GN_MMI_KEYTEST_APP";
    private static final String GN_RW_GN_MMI_KEYTEST_MENU = "GN_RW_GN_MMI_KEYTEST_MENU";
    private static final String GN_RW_GN_MMI_KEYTEST_BACK = "GN_RW_GN_MMI_KEYTEST_BACK";
    private static final String GN_RW_GN_MMI_KEYTEST_FOCUS = "GN_RW_GN_MMI_KEYTEST_FOCUS";
    private static final String GN_RW_GN_MMI_KEYTEST_HOME = "GN_RW_GN_MMI_KEYTEST_HOME";
    private static final String GN_RW_GN_MMI_RECEIVER = "GN_RW_GN_MMI_RECEIVER";
    private static final String GN_RW_GN_MMI_RECEIVER2 = "GN_RW_GN_MMI_RECEIVER2";
    private static final String GN_RW_GN_MMI_TONE = "GN_RW_GN_MMI_TONE";
    private static final String GN_RW_GN_MMI_DUALTONE = "GN_RW_GN_MMI_DUALTONE";
    private static final String GN_RW_GN_MMI_VIBRATE = "GN_RW_GN_MMI_VIBRATE";
    private static final String GN_RW_GN_MMI_MIC = "GN_RW_GN_MMI_MIC";
    private static final String GN_RW_GN_MMI_MIC2 = "GN_RW_GN_MMI_MIC2";
    private static final String GN_RW_GN_MMI_EARPHONE = "GN_RW_GN_MMI_EARPHONE";
    private static final String GN_RW_GN_MMI_HIFI = "GN_RW_GN_MMI_HIFI";
    private static final String GN_RW_GN_MMI_FM = "GN_RW_GN_MMI_FM";
    private static final String GN_RW_GN_MMI_TOUCH_PRIV_PAD = "GN_RW_GN_MMI_TOUCH_PRIV_PAD";
    private static final String GN_RW_GN_MMI_TOUCH_PAD = "GN_RW_GN_MMI_TOUCH_PAD";
    private static final String GN_RW_GN_MMI_TP_CROSS = "GN_RW_GN_MMI_TP_CROSS";
    private static final String GN_RW_GN_MMI_TP_TEN = "GN_RW_GN_MMI_TP_TEN";
    private static final String GN_RW_GN_MMI_CAMERA_BACK = "GN_RW_GN_MMI_CAMERA_BACK";
    private static final String GN_RW_GN_MMI_CAMERA_BACK2 = "GN_RW_GN_MMI_CAMERA_BACK2";
    private static final String GN_RW_GN_MMI_CAMERA_FRONT = "GN_RW_GN_MMI_CAMERA_FRONT";
    private static final String GN_RW_GN_MMI_CAMERA_FRONT2 = "GN_RW_GN_MMI_CAMERA_FRONT2";
    private static final String GN_RW_GN_MMI_SENSOR_LIGHT = "GN_RW_GN_MMI_SENSOR_LIGHT";
    private static final String GN_RW_GN_MMI_SENSOR_ACC = "GN_RW_GN_MMI_SENSOR_ACC";
    private static final String GN_RW_GN_MMI_SENSOR_COMPASS = "GN_RW_GN_MMI_SENSOR_COMPASS";
    private static final String GN_RW_GN_MMI_SENSOR_GYRO = "GN_RW_GN_MMI_SENSOR_GYRO";
    private static final String GN_RW_GN_MMI_BLUETOOTH = "GN_RW_GN_MMI_BLUETOOTH";
    private static final String GN_RW_GN_MMI_WIFI = "GN_RW_GN_MMI_WIFI";
    private static final String GN_RW_GN_MMI_WIFI5G = "GN_RW_GN_MMI_WIFI5G";
    private static final String GN_RW_GN_MMI_NFC = "GN_RW_GN_MMI_NFC";
    private static final String GN_RW_GN_MMI_NFC2 = "GN_RW_GN_MMI_NFC2";
    private static final String GN_RW_GN_MMI_IRTEST = "GN_RW_GN_MMI_IRTEST";
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 begin
    private static final String GN_RW_GN_MMI_IRTEST_GOOGLE = "GN_RW_GN_MMI_IRTEST_GOOGLE";
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 end
    private static final String GN_RW_GN_MMI_OTG = "GN_RW_GN_MMI_OTG";
    private static final String GN_RW_GN_MMI_SENSOR_GPS = "GN_RW_GN_MMI_SENSOR_GPS";
    private static final String GN_RW_GN_MMI_GPS_COC = "GN_RW_GN_MMI_GPS_COC";

    private static final String GN_RW_GN_MMI_FLASH = "GN_RW_GN_MMI_FLASH";
    private static final String GN_RW_GN_MMI_FLASH2 = "GN_RW_GN_MMI_FLASH2";
    private static final String GN_RW_GN_MMI_FLASHLIGHT = "GN_RW_GN_MMI_FLASHLIGHT";
    /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
    private static final String GN_RW_GN_MMI_FRONT_FLASH = "GN_RW_GN_MMI_FRONT_FLASH";
    /*Gionee huangjianqiang 20160420 add for CR01681501 end*/
    private static final String GN_RW_GN_MMI_FRONT_FLASH_VALUE = "GN_RW_GN_MMI_FRONT_FLASH_VALUE";

    private static final String GN_RW_GN_MMI_FINGERPRINTS = "GN_RW_GN_MMI_FINGERPRINTS";
    private static final String GN_RW_GN_MMI_FINGERPRINTS2 = "GN_RW_GN_MMI_FINGERPRINTS2";
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 begin
    private static final String GN_RW_GN_MMI_FINGERPRINTS3 = "GN_RW_GN_MMI_FINGERPRINTS3";
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 end
    private static final String GN_RW_GN_MMI_BATTERY = "GN_RW_GN_MMI_BATTERY";
    private static final String GN_RW_GN_MMI_SETCOLOR = "GN_RW_GN_MMI_SETCOLOR";
    private static final String GN_RW_GN_MMI_SENSOR_TEMPERATURE = "GN_RW_GN_MMI_SENSOR_TEMPERATURE";
    private static final String GN_RW_GN_MMI_FORCE_TOUCH = "GN_RW_GN_MMI_FORCE_TOUCH";
    private static final String GN_RW_GN_MMI_LASER = "GN_RW_GN_MMI_LASER";
    // Gionee zhangke 20160202 add for CR01634616 start
    private static final String GN_RW_GN_MMI_WCHAT_SOTER = "GN_RW_GN_MMI_WCHAT_SOTER";
    // Gionee zhangke 20160202 add for CR01634616 END
    // Gionee zhangke 20160419 add for CR01679774 start
    private static final String GN_RW_GN_MMI_QC_BATTERY = "GN_RW_GN_MMI_QC_BATTERY";
    // Gionee zhangke 20160419 add for CR01679774 end
    // Gionee zhangke 20160525 add for CR01706554 start
    private static final String GN_RW_GN_MMI_IFAA_KEY = "GN_RW_GN_MMI_IFAA_KEY";
    // Gionee zhangke 20160419 add for CR01706554 end
    // Gionee zhangke 20160902 add for CR01752769 start
    private static final String GN_RW_GN_MMI_DUAL_BACK_CAMERA = "GN_RW_GN_MMI_DUAL_BACK_CAMERA";
    // Gionee zhangke 20160902 add for CR01752769 end
    // Gionee zhangke 20160902 add for CR01756457 start
    private static final String GN_RW_GN_MMI_BACK_FLASHLIGHT_CAL = "GN_RW_GN_MMI_BACK_FLASHLIGHT_CAL";
    // Gionee zhangke 20160902 add for CR01756457 end
//Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 beign
    private static final String GN_RW_GN_MMI_IRTEST_NO_RECEIVED = "GN_RW_GN_MMI_IRTEST_NO_RECEIVED";
//Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 end
    //Gionee <GN_BSP_MMI> <chengq> <20170116> modify for ID 64213 begin
    private static final String GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST1 = "GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST1";
    //Gionee <GN_BSP_MMI> <chengq> <20170116> modify for ID 64213 end
    private static final String GN_RW_GN_MMI_SMARTPA = "GN_RW_GN_MMI_SMARTPA";
    private static final String CY_RW_CY_MMI_FACEENROLL = "CY_RW_CY_MMI_FACEENROLL";
    private static final String CY_RW_CY_MMI_FACEVERIFY = "CY_RW_CY_MMI_FACEVERIFY";
    private static final String GN_RW_GN_MMI_IRTEST3 = "GN_RW_GN_MMI_IRTEST3";

    private static final String GN_RW_GN_MMI_BRIGHTNESS_AUTOTEST2 = "GN_RW_GN_MMI_BRIGHTNESS_AUTOTEST2";
    private static final String GN_RW_GN_MMI_COLOR_AUTOTEST2 = "GN_RW_GN_MMI_COLOR_AUTOTEST2";
    private static final String GN_RW_GN_MMI_KEYS_AUTOTEST2 = "GN_RW_GN_MMI_KEYS_AUTOTEST2";
    private static final String GN_RW_GN_MMI_RECEIVER_AUTOTEST2 = "GN_RW_GN_MMI_RECEIVER_AUTOTEST2";
    private static final String GN_RW_GN_MMI_RECEIVER2_AUTOTEST2 = "GN_RW_GN_MMI_RECEIVER2_AUTOTEST2";
    private static final String GN_RW_GN_MMI_TONE_AUTOTEST2 = "GN_RW_GN_MMI_TONE_AUTOTEST2";
    private static final String GN_RW_GN_MMI_DUALTONE_AUTOTEST2 = "GN_RW_GN_MMI_DUALTONE_AUTOTEST2";
    private static final String GN_RW_GN_MMI_VIBRATE_AUTOTEST2 = "GN_RW_GN_MMI_VIBRATE_AUTOTEST2";
    private static final String GN_RW_GN_MMI_MIC_AUTOTEST2 = "GN_RW_GN_MMI_MIC_AUTOTEST2";
    private static final String GN_RW_GN_MMI_MIC2_AUTOTEST2 = "GN_RW_GN_MMI_MIC2_AUTOTEST2";
    private static final String GN_RW_GN_MMI_EARPHONE_AUTOTEST2 = "GN_RW_GN_MMI_EARPHONE_AUTOTEST2";
    private static final String GN_RW_GN_MMI_HIFI_AUTOTEST2 = "GN_RW_GN_MMI_HIFI_AUTOTEST2";
    private static final String GN_RW_GN_MMI_FM_AUTOTEST2 = "GN_RW_GN_MMI_FM_AUTOTEST2";
    private static final String GN_RW_GN_MMI_TOUCH_PRIV_PAD_AUTOTEST2 = "GN_RW_GN_MMI_TOUCH_PRIV_PAD_AUTOTEST2";
    private static final String GN_RW_GN_MMI_TOUCH_PAD_AUTOTEST2 = "GN_RW_GN_MMI_TOUCH_PAD_AUTOTEST2";
    private static final String GN_RW_GN_MMI_CAMERA_BACK_AUTOTEST2 = "GN_RW_GN_MMI_CAMERA_BACK_AUTOTEST2";
    private static final String GN_RW_GN_MMI_CAMERA_BACK2_AUTOTEST2 = "GN_RW_GN_MMI_CAMERA_BACK2_AUTOTEST2";
    private static final String GN_RW_GN_MMI_CAMERA_FRONT_AUTOTEST2 = "GN_RW_GN_MMI_CAMERA_FRONT_AUTOTEST2";
	private static final String GN_RW_GN_MMI_CAMERA_FRONT2_AUTOTEST2 = "GN_RW_GN_MMI_CAMERA_FRONT2_AUTOTEST2";
    private static final String GN_RW_GN_MMI_SENSOR_LIGHT_AUTOTEST2 = "GN_RW_GN_MMI_SENSOR_LIGHT_AUTOTEST2";
    private static final String GN_RW_GN_MMI_SENSOR_ACC_AUTOTEST2 = "GN_RW_GN_MMI_SENSOR_ACC_AUTOTEST2";
    private static final String GN_RW_GN_MMI_SENSOR_COMPASS_AUTOTEST2 = "GN_RW_GN_MMI_SENSOR_COMPASS_AUTOTEST2";
    private static final String GN_RW_GN_MMI_SENSOR_GYRO_AUTOTEST2 = "GN_RW_GN_MMI_SENSOR_GYRO_AUTOTEST2";
    private static final String GN_RW_GN_MMI_BLUETOOTH_AUTOTEST2 = "GN_RW_GN_MMI_BLUETOOTH_AUTOTEST2";
    private static final String GN_RW_GN_MMI_WIFI_AUTOTEST2 = "GN_RW_GN_MMI_WIFI_AUTOTEST2";
    private static final String GN_RW_GN_MMI_WIFI5G_AUTOTEST2 = "GN_RW_GN_MMI_WIFI5G_AUTOTEST2";
    private static final String GN_RW_GN_MMI_NFC_AUTOTEST2 = "GN_RW_GN_MMI_NFC_AUTOTEST2";
    private static final String GN_RW_GN_MMI_NFC2_AUTOTEST2 = "GN_RW_GN_MMI_NFC2_AUTOTEST2";
    private static final String GN_RW_GN_MMI_IRTEST_AUTOTEST2 = "GN_RW_GN_MMI_IRTEST_AUTOTEST2";
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 begin
    private static final String GN_RW_GN_MMI_IRTEST_GOOGLE_AUTOTEST2 = "GN_RW_GN_MMI_IRTEST_GOOGLE_AUTOTEST2";
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 end
    private static final String GN_RW_GN_MMI_OTG_AUTOTEST2 = "GN_RW_GN_MMI_OTG_AUTOTEST2";
    private static final String GN_RW_GN_MMI_SENSOR_GPS_AUTOTEST2 = "GN_RW_GN_MMI_SENSOR_GPS_AUTOTEST2";
    private static final String GN_RW_GN_MMI_FLASH_AUTOTEST2 = "GN_RW_GN_MMI_FLASH_AUTOTEST2";
    private static final String GN_RW_GN_MMI_FLASH2_AUTOTEST2 = "GN_RW_GN_MMI_FLASH2_AUTOTEST2";
    private static final String GN_RW_GN_MMI_FLASHLIGHT_AUTOTEST2 = "GN_RW_GN_MMI_FLASHLIGHT_AUTOTEST2";
    /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
    private static final String GN_RW_GN_MMI_FRONT_FLASH_AUTOTEST2 = "GN_RW_GN_MMI_FRONT_FLASH_AUTOTEST2";
    /*Gionee huangjianqiang 20160420 add for CR01681501 end*/
    private static final String GN_RW_GN_MMI_FINGERPRINTS_AUTOTEST2 = "GN_RW_GN_MMI_FINGERPRINTS_AUTOTEST2";
    private static final String GN_RW_GN_MMI_FINGERPRINTS2_AUTOTEST2 = "GN_RW_GN_MMI_FINGERPRINTS2_AUTOTEST2";
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 begin
    private static final String GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST2 = "GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST2";
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 end
    private static final String GN_RW_GN_MMI_FORCE_TOUCH_AUTOTEST2 = "GN_RW_GN_MMI_FORCE_TOUCH_AUTOTEST2";
    private static final String GN_RW_GN_MMI_BATTERY_AUTOTEST2 = "GN_RW_GN_MMI_BATTERY_AUTOTEST2";
    //Gionee <GN_BSP_MMI> <chengq> <20170107> modify for ID 60451 begin
    private static final String GN_RW_GN_MMI_QC_BATTERY_AUTOTEST2 = "GN_RW_GN_MMI_QC_BATTERY_AUTOTEST2";
    //Gionee <GN_BSP_MMI> <chengq> <20170107> modify for ID 60451 begin

    //Gionee <GN_BSP_MMI> <chengq> <20170116> modify for ID 64213 begin
    public static boolean GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST1_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170116> modify for ID 64213 end
    private static final String GN_RW_GN_MMI_SMARTPA_AUTOTEST2 = "GN_RW_GN_MMI_SMARTPA_AUTOTEST2";
    private static final String GN_RW_GN_MMI_FACEENROLL_AUTOTEST2 = "GN_RW_GN_MMI_FACEENROLL_AUTOTEST2";
    private static final String GN_RW_GN_MMI_FACEVERIFY_AUTOTEST2 = "GN_RW_GN_MMI_FACEVERIFY_AUTOTEST2";
    // Gionee zhangke 20151014 add for CR01567923 start
    public static boolean GN_RW_GN_MMI_BRIGHTNESS_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_COLOR_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYS_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_RECEIVER_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_RECEIVER2_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_TONE_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_DUALTONE_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_VIBRATE_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_MIC_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_MIC2_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_EARPHONE_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_HIFI_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_FM_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_TOUCH_PRIV_PAD_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_TOUCH_PAD_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_CAMERA_BACK_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_CAMERA_BACK2_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_CAMERA_FRONT_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_CAMERA_FRONT2_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_LIGHT_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_ACC_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_COMPASS_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_GYRO_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_BLUETOOTH_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_WIFI_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_WIFI5G_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_NFC_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_NFC2_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_IRTEST_AUTOTEST2_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 begin
    public static boolean GN_RW_GN_MMI_IRTEST_GOOGLE_AUTOTEST2_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 end
    public static boolean GN_RW_GN_MMI_OTG_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_GPS_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_FLASH_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_FLASH2_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_FLASHLIGHT_AUTOTEST2_SUPPORT;
    /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
    public static boolean GN_RW_GN_MMI_FRONT_FLASH_AUTOTEST2_SUPPORT;
    /*Gionee huangjianqiang 20160420 add for CR01681501 end*/

    public static boolean GN_RW_GN_MMI_FINGERPRINTS_AUTOTEST2_SUPPORT;
    public static boolean GN_RW_GN_MMI_FINGERPRINTS2_AUTOTEST2_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 begin
    public static boolean GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST2_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 end
    public static boolean GN_RW_GN_MMI_BATTERY_AUTOTEST2_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170107> modify for ID 60451 begin
    public static boolean GN_RW_GN_MMI_QC_BATTERY_AUTOTEST2_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170107> modify for ID 60451 end
    // Gionee zhangke 20151128 add for CR01591381 start
    public static boolean GN_RW_GN_MMI_FORCE_TOUCH_AUTOTEST2_SUPPORT;
    // Gionee zhangke 20151128 add for CR01591381 end
    public static boolean GN_RW_GN_MMI_SMARTPA_AUTOTEST2_SUPPORT;
    public static boolean CY_RW_CY_MMI_FACEENROLL_AUTOTEST2_SUPPORT;
    public static boolean CY_RW_CY_MMI_FACEVERIFY_AUTOTEST2_SUPPORT;
    // Gionee zhangke 20151014 add for CR01567923 end
    // Gionee zhangke 20151019 add for CR01571097 start
    public static boolean GN_RW_GN_MMI_AUTOTEST2_SUPPORT;
    //Gionee zhangke 20160310 add for CR01650400 start
    public static boolean GN_RW_GN_MMI_RPMB_SUPPORT;
    //Gionee zhangke 20160310 add for CR01650400 end

    public static boolean BACKUP_TO_PRODUCTINFO=true;
    // single test items start
    // software version info start
    public static boolean GN_RW_GN_MMI_SW_VERSION_SUPPORT;
    public static boolean GN_RW_GN_MMI_WCDMA_SUPPORT;
    public static boolean GN_RW_GN_MMI_CDMA_SUPPORT;
    public static boolean GN_RW_GN_MMI_TDSCDMA_SUPPORT;
    public static boolean GN_RW_GN_MMI_LTETDD_SUPPORT;
    public static boolean GN_RW_GN_MMI_LTEFDD_SUPPORT;
    //Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 beign
    public static boolean GN_RW_GN_MMI_ANT_SUPPORT;
    //Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 end
    //Gionee <GN_BSP_MMI> <chengq> <20170412> add for ID 91383 begin
    public static boolean GN_RW_GN_MMI_GM3_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170412> add for ID 91383 end
    public static boolean GN_RW_GN_MMI_EFUSE_SUPPORT;
    /*Gionee futao 20160330 modify for CR01663704 */
    public static boolean GN_RW_GN_MMI_GSM_SUPPORT = true;
    // software version info end

    public static boolean GN_RW_GN_MMI_SCREEN_BRIGHTNESS_SUPPORT;
    public static boolean GN_RW_GN_MMI_LCD_SUPPORT;

    // keys start
    public static boolean GN_RW_GN_MMI_KEYTEST_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_MENU_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_APP_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_SEARCH_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_CAMERA_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_FOCUS_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_HALL_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_BACK_SUPPORT;
    public static boolean GN_RW_GN_MMI_KEYTEST_HOME_SUPPORT;
    // keys end

    public static boolean GN_RW_GN_MMI_RECEIVER_SUPPORT;
    public static boolean GN_RW_GN_MMI_RECEIVER2_SUPPORT;
    public static boolean GN_RW_GN_MMI_TONE_SUPPORT;
    public static boolean GN_RW_GN_MMI_DUALTONE_SUPPORT;
    public static boolean GN_RW_GN_MMI_VIBRATE_SUPPORT;
    public static boolean GN_RW_GN_MMI_MIC_SUPPORT;
    public static boolean GN_RW_GN_MMI_MIC2_SUPPORT;
    public static boolean GN_RW_GN_MMI_EARPHONE_SUPPORT;
    public static boolean GN_RW_GN_MMI_HIFI_SUPPORT;
    public static boolean GN_RW_GN_MMI_FM_SUPPORT;
    public static boolean GN_RW_GN_MMI_TOUCH_PRIV_PAD_SUPPORT;

    // touch pad
    public static boolean GN_RW_GN_MMI_TOUCH_PAD_SUPPORT;
    public static boolean GN_RW_GN_MMI_TP_CROSS_SUPPORT;
    public static boolean GN_RW_GN_MMI_TP_TEN_SUPPORT;
    // touch pad

    public static boolean GN_RW_GN_MMI_CAMERA_FRONT_SUPPORT;
    public static boolean GN_RW_GN_MMI_CAMERA_FRONT2_SUPPORT;
    public static boolean GN_RW_GN_MMI_CAMERA_BACK_SUPPORT;
    public static boolean GN_RW_GN_MMI_CAMERA_BACK2_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_LIGHT_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_ACC_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_COMPASS_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_GYRO_SUPPORT;
    public static boolean GN_RW_GN_MMI_BLUETOOTH_SUPPORT;
    public static boolean GN_RW_GN_MMI_WIFI_SUPPORT;
    public static boolean GN_RW_GN_MMI_WIFI5G_SUPPORT;
    public static boolean GN_RW_GN_MMI_NFC_SUPPORT;
    public static boolean GN_RW_GN_MMI_NFC2_SUPPORT;
    public static boolean GN_RW_GN_MMI_IRTEST_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 begin
    public static boolean GN_RW_GN_MMI_IRTEST_GOOGLE_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 end
    public static boolean GN_RW_GN_MMI_OTG_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_GPS_SUPPORT;
    public static boolean GN_RW_GN_MMI_GPS_COC_SUPPORT;
    public static boolean GN_RW_GN_MMI_FLASH_SUPPORT;
    public static boolean GN_RW_GN_MMI_FLASH2_SUPPORT;
    public static boolean GN_RW_GN_MMI_FLASHLIGHT_SUPPORT;
    /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
    public static boolean GN_RW_GN_MMI_FRONT_FLASH_SUPPORT;
    /*Gionee huangjianqiang 20160420 add for CR01681501 end*/
    public static int GN_RW_GN_MMI_FRONT_FLASH_SUPPORT_VALUE;
    public static boolean GN_RW_GN_MMI_FINGERPRINTS_SUPPORT;
    public static boolean GN_RW_GN_MMI_FINGERPRINTS2_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 begin
    public static boolean GN_RW_GN_MMI_FINGERPRINTS3_SUPPORT;
    //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 end
    public static boolean GN_RW_GN_MMI_BATTERY_SUPPORT;
    public static boolean GN_RW_GN_MMI_SETCOLOR_SUPPORT;
    public static boolean GN_RW_GN_MMI_SENSOR_TEMPERATURE_SUPPORT;
    // Gionee zhangke 20151128 add for CR01591381 start
    public static boolean GN_RW_GN_MMI_FORCE_TOUCH_SUPPORT;
    // Gionee zhangke 20151128 add for CR01591381 end
    // Gionee zhangke 20151128 add for CR01588796 start
    public static boolean GN_RW_GN_MMI_LASER_SUPPORT;
    // Gionee zhangke 20151128 add for CR01588796 end
    // Gionee zhangke 20160202 add for CR01634616 start
    public static boolean GN_RW_GN_MMI_WCHAT_SOTER_SUPPORT;
    // Gionee zhangke 20160202 add for CR01634616 end
    // Gionee zhangke 20160419 add for CR01679774 start
    public static boolean GN_RW_GN_MMI_QC_BATTERY_SUPPORT;
    // Gionee zhangke 20160419 add for CR01679774 end
    // Gionee zhangke 20160525 add for CR01706554 start
    public static boolean GN_RW_GN_MMI_IFAA_KEY_SUPPORT;
    // Gionee zhangke 20160419 add for CR01706554 end
    // Gionee zhangke 20160902 add for CR01752769 start
    public static boolean GN_RW_GN_MMI_DUAL_BACK_CAMERA_SUPPORT;
    // Gionee zhangke 20160902 add for CR01752769 end
    // Gionee zhangke 20160902 add for CR01756457 start
    public static boolean GN_RW_GN_MMI_BACK_FLASHLIGHT_CAL_SUPPORT;
    // Gionee zhangke 20160902 add for CR01756457 end
//Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 beign
    public static boolean GN_RW_GN_MMI_IRTEST_NO_RECEIVED_SUPPORT;
//Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 end
    public static boolean GN_RW_GN_MMI_SMARTPA_SUPPORT;
    public static boolean CY_RW_CY_MMI_FACEENROLL_SUPPORT;
    public static boolean CY_RW_CY_MMI_FACEVERIFY_SUPPORT;
    public static boolean GN_RW_GN_MMI_IRTEST3_SUPPORT;
    // single test items end
    // Gionee zhangke 20151019 add for CR01571097 end

    public static void initMmiXml() {
        FileReader dbReader;

        final File dbConfigFile = new File(GN_MMI_CONFIG_FILE);

        try {
            dbReader = new FileReader(dbConfigFile);
        } catch (FileNotFoundException e) {
            DswLog.e(TAG, "Can't open " + GN_MMI_CONFIG_FILE);
            return;
        }
        try {
            XmlPullParser parser = Xml.newPullParser();
            parser.setInput(dbReader);
            XmlUtils.beginDocument(parser, "gnmmi");
            int eventType = parser.getEventType();
            while (eventType != XmlPullParser.END_DOCUMENT) {
                XmlUtils.nextElement(parser);
                String gnmmi = parser.getName();

                String name = parser.getAttributeValue(null, "name");
                String value = parser.getAttributeValue(null, "value");
                if (GN_RW_GN_MMI_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_RPMB.equals(name)) {
                    GN_RW_GN_MMI_RPMB_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_BACKUP_TO_PRODUCTINFO.equals(name)) {
//                    Gionee tanbotao 20160906 modify for CR01754023 start
//                    BACKUP_TO_PRODUCTINFO = Boolean.parseBoolean(value);
                    BACKUP_TO_PRODUCTINFO = true;
//                    Gionee tanbotao 20160906 modify for CR01754023 end
                } else if (GN_RW_GN_MMI_SW_VERSION.equals(name)) {
                    GN_RW_GN_MMI_SW_VERSION_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_WCDMA.equals(name)) {
                    GN_RW_GN_MMI_WCDMA_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_CDMA.equals(name)) {
                    GN_RW_GN_MMI_CDMA_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TDSCDMA.equals(name)) {
                    GN_RW_GN_MMI_TDSCDMA_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_LTETDD.equals(name)) {
                    GN_RW_GN_MMI_LTETDD_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_LTEFDD.equals(name)) {
                    GN_RW_GN_MMI_LTEFDD_SUPPORT = Boolean.parseBoolean(value);
                    //Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 beign
                } else if (GN_RW_GN_MMI_ANT.equals(name)) {
                    GN_RW_GN_MMI_ANT_SUPPORT = Boolean.parseBoolean(value);
                    //Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 end
                } //Gionee <GN_BSP_MMI> <chengq> <20170412> add for ID 91383 begin
				  else if (GN_RW_GN_MMI_GM3.equals(name)) {
                    GN_RW_GN_MMI_GM3_SUPPORT= Boolean.parseBoolean(value);
                  //Gionee <GN_BSP_MMI> <chengq> <20170412> add for ID 91383 end
                } else if (GN_RW_GN_MMI_EFUSE.equals(name)) {
                    GN_RW_GN_MMI_EFUSE_SUPPORT= Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SCREEN_BRIGHTNESS.equals(name)) {
                    GN_RW_GN_MMI_SCREEN_BRIGHTNESS_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_LCD.equals(name)) {
                    GN_RW_GN_MMI_LCD_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_MENU.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_MENU_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_APP.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_APP_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_SEARCH.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_SEARCH_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_CAMERA.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_CAMERA_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_FOCUS.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_FOCUS_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_HALL.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_HALL_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_BACK.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_BACK_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYTEST_HOME.equals(name)) {
                    GN_RW_GN_MMI_KEYTEST_HOME_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_RECEIVER.equals(name)) {
                    GN_RW_GN_MMI_RECEIVER_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_RECEIVER2.equals(name)) {
                    GN_RW_GN_MMI_RECEIVER2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TONE.equals(name)) {
                    GN_RW_GN_MMI_TONE_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_DUALTONE.equals(name)) {
                    GN_RW_GN_MMI_DUALTONE_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_VIBRATE.equals(name)) {
                    GN_RW_GN_MMI_VIBRATE_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_MIC.equals(name)) {
                    GN_RW_GN_MMI_MIC_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_MIC2.equals(name)) {
                    GN_RW_GN_MMI_MIC2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_EARPHONE.equals(name)) {
                    GN_RW_GN_MMI_EARPHONE_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_HIFI.equals(name)) {
                    GN_RW_GN_MMI_HIFI_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FM.equals(name)) {
                    GN_RW_GN_MMI_FM_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TOUCH_PRIV_PAD.equals(name)) {
                    GN_RW_GN_MMI_TOUCH_PRIV_PAD_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TOUCH_PAD.equals(name)) {
                    GN_RW_GN_MMI_TOUCH_PAD_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TP_CROSS.equals(name)) {
                    GN_RW_GN_MMI_TP_CROSS_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TP_TEN.equals(name)) {
                    GN_RW_GN_MMI_TP_TEN_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_CAMERA_FRONT.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_FRONT_SUPPORT = Boolean.parseBoolean(value);
                } //Gionee <GN_BSP_MMI> <lifeilong> <20170311> modify for ID 82014 begin 
                  else if (GN_RW_GN_MMI_CAMERA_FRONT2.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_FRONT2_SUPPORT = Boolean.parseBoolean(value);
                  //Gionee <GN_BSP_MMI> <lifeilong> <20170311> modify for ID 82014 end
                } else if (GN_RW_GN_MMI_CAMERA_BACK.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_BACK_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_CAMERA_BACK2.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_BACK2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_LIGHT.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_LIGHT_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_ACC.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_ACC_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_COMPASS.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_COMPASS_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_GYRO.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_GYRO_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_BLUETOOTH.equals(name)) {
                    GN_RW_GN_MMI_BLUETOOTH_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_WIFI.equals(name)) {
                    GN_RW_GN_MMI_WIFI_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_WIFI5G.equals(name)) {
                    GN_RW_GN_MMI_WIFI5G_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_NFC.equals(name)) {
                    GN_RW_GN_MMI_NFC_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_NFC2.equals(name)) {
                    GN_RW_GN_MMI_NFC2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_IRTEST.equals(name)) {
                    GN_RW_GN_MMI_IRTEST_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 begin
                } else if (GN_RW_GN_MMI_IRTEST_GOOGLE.equals(name)) {
                    GN_RW_GN_MMI_IRTEST_GOOGLE_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 end
                } else if (GN_RW_GN_MMI_IRTEST3.equals(name)) {
                    GN_RW_GN_MMI_IRTEST3_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_OTG.equals(name)) {
                    GN_RW_GN_MMI_OTG_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_GPS.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_GPS_SUPPORT = Boolean.parseBoolean(value);
                }
                //Gionee <GN_BSP_MMI> <chengq> <20170705> modify for ID 165507 begin
                else if (GN_RW_GN_MMI_GPS_COC.equals(name)) {
                    GN_RW_GN_MMI_GPS_COC_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170705> modify for ID 165507 end
                } else if (GN_RW_GN_MMI_FLASH.equals(name)) {
                    GN_RW_GN_MMI_FLASH_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FLASH2.equals(name)) {
                    GN_RW_GN_MMI_FLASH2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FLASHLIGHT.equals(name)) {
                    GN_RW_GN_MMI_FLASHLIGHT_SUPPORT = Boolean.parseBoolean(value);

                /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
                } else if (GN_RW_GN_MMI_FRONT_FLASH.equals(name)) {
                    GN_RW_GN_MMI_FRONT_FLASH_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170225> add for ID 66991 begin
                    if (GN_RW_GN_MMI_FRONT_FLASH_SUPPORT)
                        GN_RW_GN_MMI_FRONT_FLASH_SUPPORT_VALUE = 1;
                /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
                } else if (GN_RW_GN_MMI_FRONT_FLASH_VALUE.equals(name)) {
                    GN_RW_GN_MMI_FRONT_FLASH_SUPPORT_VALUE = Integer.parseInt(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170225> add for ID 66991 end
                } else if (GN_RW_GN_MMI_FINGERPRINTS.equals(name)) {
                    GN_RW_GN_MMI_FINGERPRINTS_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FINGERPRINTS2.equals(name)) {
                    GN_RW_GN_MMI_FINGERPRINTS2_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 begin
                } else if (GN_RW_GN_MMI_FINGERPRINTS3.equals(name)) {
                    GN_RW_GN_MMI_FINGERPRINTS3_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 end
                } else if (GN_RW_GN_MMI_BATTERY.equals(name)) {
                    GN_RW_GN_MMI_BATTERY_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_QC_BATTERY.equals(name)) {
                    GN_RW_GN_MMI_QC_BATTERY_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SETCOLOR.equals(name)) {
                    GN_RW_GN_MMI_SETCOLOR_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_TEMPERATURE.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_TEMPERATURE_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FORCE_TOUCH.equals(name)) {
                    GN_RW_GN_MMI_FORCE_TOUCH_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_LASER.equals(name)) {
                    GN_RW_GN_MMI_LASER_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_WCHAT_SOTER.equals(name)) {
                    GN_RW_GN_MMI_WCHAT_SOTER_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_IFAA_KEY.equals(name)) {// Gionee zhangke 20160525 add for CR01706554
                    GN_RW_GN_MMI_IFAA_KEY_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_DUAL_BACK_CAMERA.equals(name)) {
                    GN_RW_GN_MMI_DUAL_BACK_CAMERA_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_BACK_FLASHLIGHT_CAL.equals(name)) {
                    GN_RW_GN_MMI_BACK_FLASHLIGHT_CAL_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170116> modify for ID 64213 begin
                } else if (GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST1.equals(name)) {
                    GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST1_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170116> modify for ID 64213 end
                //Chenyee <CY_BSP_MMI> <chengq> <20170831> add for CR 169245 begin
                } else if (GN_RW_GN_MMI_SMARTPA.equals(name)) {
                    GN_RW_GN_MMI_SMARTPA_SUPPORT = Boolean.parseBoolean(value);
                //Chenyee <CY_BSP_MMI> <chengq> <20170831> add for CR 169245 end
                } else if (CY_RW_CY_MMI_FACEENROLL.equals(name)) {
                    CY_RW_CY_MMI_FACEENROLL_SUPPORT = Boolean.parseBoolean(value);
                } else if (CY_RW_CY_MMI_FACEVERIFY.equals(name)) {
                    CY_RW_CY_MMI_FACEVERIFY_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_BRIGHTNESS_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_BRIGHTNESS_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_COLOR_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_COLOR_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_KEYS_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_KEYS_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_RECEIVER_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_RECEIVER_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_RECEIVER2_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_RECEIVER2_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TONE_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_TONE_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_DUALTONE_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_DUALTONE_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_VIBRATE_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_VIBRATE_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_MIC_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_MIC_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_MIC2_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_MIC2_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_EARPHONE_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_EARPHONE_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_HIFI_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_HIFI_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FM_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FM_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TOUCH_PRIV_PAD_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_TOUCH_PRIV_PAD_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_TOUCH_PAD_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_TOUCH_PAD_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_CAMERA_BACK_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_BACK_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_CAMERA_BACK2_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_BACK2_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_CAMERA_FRONT_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_FRONT_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_CAMERA_FRONT2_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_CAMERA_FRONT2_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                }else if (GN_RW_GN_MMI_SENSOR_LIGHT_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_LIGHT_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_ACC_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_ACC_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_COMPASS_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_COMPASS_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_GYRO_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_GYRO_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_BLUETOOTH_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_BLUETOOTH_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_WIFI_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_WIFI_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_WIFI5G_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_WIFI5G_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_NFC_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_NFC_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_NFC2_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_NFC2_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_IRTEST_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_IRTEST_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 begin
                } else if (GN_RW_GN_MMI_IRTEST_GOOGLE_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_IRTEST_GOOGLE_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170215> modify for ID 68092 end
                } else if (GN_RW_GN_MMI_OTG_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_OTG_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SENSOR_GPS_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_SENSOR_GPS_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FLASH_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FLASH_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FLASH2_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FLASH2_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FLASHLIGHT_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FLASHLIGHT_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);

                /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
                } else if (GN_RW_GN_MMI_FRONT_FLASH_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FRONT_FLASH_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                 /*Gionee huangjianqiang 20160420 add for CR01681501 begin*/
                } else if (GN_RW_GN_MMI_FINGERPRINTS_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FINGERPRINTS_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FINGERPRINTS2_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FINGERPRINTS2_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 begin
                } else if (GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FINGERPRINTS3_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                //Gionee <GN_BSP_MMI> <chengq> <20170109> add for ID 61637 end
                } else if (GN_RW_GN_MMI_BATTERY_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_BATTERY_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_QC_BATTERY_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_QC_BATTERY_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FORCE_TOUCH_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_FORCE_TOUCH_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
//Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 beign
                } else if (GN_RW_GN_MMI_IRTEST_NO_RECEIVED.equals(name)) {
                    GN_RW_GN_MMI_IRTEST_NO_RECEIVED_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_SMARTPA_AUTOTEST2.equals(name)) {
                    GN_RW_GN_MMI_SMARTPA_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FACEENROLL_AUTOTEST2.equals(name)) {
                    CY_RW_CY_MMI_FACEENROLL_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                } else if (GN_RW_GN_MMI_FACEVERIFY_AUTOTEST2.equals(name)) {
                    CY_RW_CY_MMI_FACEVERIFY_AUTOTEST2_SUPPORT = Boolean.parseBoolean(value);
                }
//Gionee <Oversea_Bug> <tanbotao> <20161124> for #28369 end
                DswLog.i(TAG, "name=" + name + ";value=" + value);
                eventType = parser.next();
            }
        } catch (XmlPullParserException e) {
            DswLog.e(TAG, "Exception  config parser " + e);
        } catch (Exception e) {
            DswLog.e(TAG, "Exception in font config parser " + e);
        } finally {
            try {
                dbReader.close();
            } catch (Exception e) {
            }
        }
        /*Gionee futao 20160330 modify for CR01663704 begin*/
        getMMIProp();
        /*Gionee futao 20160330 modify for CR01663704 end*/
    }

    /*Gionee futao 20160330 modify for CR01663704 begin*/
    public static void getMMIProp() {
        GN_RW_GN_MMI_GSM_SUPPORT
                = "yes".equals(SystemProperties.get("gn.mmi.gsm", "yes"));
        GN_RW_GN_MMI_WCDMA_SUPPORT
                = "yes".equals(SystemProperties.get("gn.mmi.wcdma", "no"));
        GN_RW_GN_MMI_CDMA_SUPPORT
                = "yes".equals(SystemProperties.get("gn.mmi.cdma", "no"));
        GN_RW_GN_MMI_TDSCDMA_SUPPORT
                = "yes".equals(SystemProperties.get("gn.mmi.tdscdma", "no"));
        GN_RW_GN_MMI_LTETDD_SUPPORT
                = "yes".equals(SystemProperties.get("gn.mmi.ltetdd", "no"));
        GN_RW_GN_MMI_LTEFDD_SUPPORT
                = "yes".equals(SystemProperties.get("gn.mmi.ltefdd", "no"));
        GN_RW_GN_MMI_SETCOLOR_SUPPORT
                = (("yes".equals(SystemProperties.get("gn.mmi.setcolor", "no")))
                && ("yes".equals(SystemProperties.get("ro.gn.dynamic.theme.supprot", "no"))));
    }
    /*Gionee futao 20160330 modify for CR01663704 end*/

}
