#!/bin/bash

export PATH=/home/billy/work/uit/aosp/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:/home/billy/work/uit/aosp/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/:$PATH
export ARCH=arm64
#export CROSS_COMPILE=arm-linux-gnueabi-
#export CROSS_COMPILE=arm-linux-androideabi-
#export CROSS_COMPILE=aarch64-linux-android-
export CROSS_COMPILE=aarch64-linux-gnu-

#rm -rf out/*
#make mrproper

#scripts/kconfig/merge_config.sh arch/arm64/configs/billy_BCM2835_defconfig kernel/configs/android-base-qemu.config kernel/configs/android-recommended-qemu.config
#scripts/kconfig/merge_config.sh arch/arm64/configs/defconfig kernel/configs/android-base.config kernel/configs/android-recommended.config



#read


#cp .config out

#make mrproper
#make O=./out menuconfig

#make O=./out -j16

cross_compile=aarch64-linux-gnu-
#make CROSS_COMPILE=$cross_compile ARCH=arm64 O=./out_aarch64 defconfig
#make CROSS_COMPILE=$cross_compile ARCH=arm64 O=./out_aarch64 menuconfig
make CROSS_COMPILE=$cross_compile ARCH=arm64 O=./out_aarch64 -j8
